### ISSUE TITLE
Use as an npm module

### ISSUE THREAD

**Issue by xavdid** [basti1302/repoman#28]
Hey there! So we've been using this and it's really neat. 

One this is that it would be really cool to use it programmatically in js code. 

I looked into doing this briefly myself. While possible, there's some refactoring that would need to be done since things like reading the config file are done in `cli.js`. If that was all moved down, then the cli itself could be written to simply consume the commands. For extra points, being able to grab console output would be great. An ideal situation would be the following: 

```js
const repoman = require('repoman')

repoman.init() // reads config, clones all repos
repoman.exec('ls')
  // array of output objects like [{code: 0, stdout: 'filea\nfileb\n', stderr: ''}]
  .then(output => {
    // filter on output that went bed
    // act accordingly
  })
```

I realize this is a pretty big change, but it would be awesome!

**Comment by basti1302** [comment]
I agree that this would be nice.

That said, I won't be doing this, at least not anytime soon. 

A PR would be welcome though.

**Comment by basti1302** [comment]
Closing this due to lack of interest/contributions.
